### ISSUE TITLE
API uses unexported constants

### ISSUE THREAD

**Issue by tv42** [symbolicsoft/kyber-k2so#1]
```
func KemEncrypt(publicKey [paramsPublicKeyBytes]byte) ([paramsIndcpaBytes]byte, [paramsSymBytes]byte, error) {
```

There's no way for anyone to use this API for real, because the array sizes cannot be referenced outside this package.

Try to move your tests from `package kyberk2so` to `package kyberk2so_test` to feel the pain yourself.

**Comment by kaepora** [comment]
@tv42 Why do we need to reference the array sizes outside of the package?

This works perfectly fine:

```go
package main

import (
	"encoding/hex"
	"fmt"

	kyberk2so "github.com/symbolicsoft/kyber-k2so"
)

func main() {
	privateKey, publicKey, _ := kyberk2so.KemKeypair768()
	ciphertext, ssA, _ := kyberk2so.KemEncrypt768(publicKey)
	ssB, _ := kyberk2so.KemDecrypt768(ciphertext, privateKey)
	fmt.Println(hex.EncodeToString(ssA[:])) // Should be equal to ssB
	fmt.Println(hex.EncodeToString(ssB[:])) // Should be equal to ssA
	fmt.Println(len(ciphertext)) // 1088
	fmt.Println(len(privateKey)) // 2400
}
```

That being said I don't mind exporting the relevant constants and will do so now.

**Comment by kaepora** [comment]
v0.0.5, tagged and released now.

**Comment by tv42** [comment]
Try storing a key in a struct field or passing it as a function argument.

**Comment by kaepora** [comment]
@tv42 Yes, I later understood why this is important. I hope that the fix is sufficient. Please let me know if you run into further problems.
