### ISSUE TITLE
Possible variable-time division when decapsulating

### ISSUE THREAD

**Issue by xvzcf** [symbolicsoft/kyber-k2so#7]
This bit of code is used in compressing a polynomial ring element into a (secret) message: https://github.com/symbolicsoft/kyber-k2so/blob/ffaf2ee82ba71d2ed80e063595715e6dcfb345d0/poly.go#L127

To do so, it performs a division by Q that might not necessarily compile to a multiplication instruction: looking at the output of some C compilers using https://godbolt.org/z/sKn3TKKGq and https://godbolt.org/z/8GqKoTfYh for example, a division instruction is emitted even when -O3 is specified. Should a division instruction be emitted, its execution time would likely be variable and leak information about its secret input.

We reported a similar issue in the CRYSTALS-Kyber reference implementation; you may want to use their fix: https://github.com/pq-crystals/kyber/commit/dda29cc63af721981ee2c831cf00822e69be3220

**Comment by nadimkobeissi** [comment]
@xvzcf Hi Goutam,

Yes, I see this blowing up on the PQ-Crypto mailing list just now. I'll be looking at implementing a fix ASAP. Thanks.

**Comment by nadimkobeissi** [comment]
@xvzcf Could you please verify the correctness of this fix proposed at https://github.com/symbolicsoft/kyber-k2so/pull/8 ?

**Comment by nadimkobeissi** [comment]
Fix was reviewed by Karthikeyan Bhargavan and Peter Schwabe and is now merged.
